# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-06 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
